### PR TITLE
backported to APEX 5.0

### PR DESCRIPTION
**Pull request by jeffreykemp**

### CODE REVIEW

**Comment by vincentmorneau** [comment]
What exactly is the difference? I just compared the source and it seem identical.

**Comment by Dani3lSun** [comment]
The source PL/SQL code is normally the same, but you have to export the plugin from an APEX 5.0 instance, because the export API of APEX is not backward compatible...
If you export with 5.1 you are only compatible to 5.1 and above, if you export with 5.0 you are compatible with 5.0 and above...
I created a feature request (backward compatible export API) a while ago, maybe you can upvote this! :)
https://apex.oracle.com/pls/apex/f?p=55447:19:0::NO:19:P19_ID:111173302180519140544235057580870503859

**Comment by jeffreykemp** [comment]
Probably the only difference is this line:

p_release=>'5.0.4.00.12'

You could _probably_ just update your version of the script and it would just work, since it seems all the API calls and attributes this plugin import script use appear to be identical between 5.0 and 5.1. However, I'm not sure that would be supported by Oracle.

**Comment by Dani3lSun** [comment]
Yeah true, the difference between this 2 versions shouldn´t be more than ~1,2 lines:
```
# APEX 5.1
 p_version_yyyy_mm_dd=>'2016.08.24'
,p_release=>'5.1.2.00.09'

# APEX 5.0
 p_version_yyyy_mm_dd=>'2013.01.01'
,p_release=>'5.0.4.00.12'
```
The difference from 4.2 to 5.0 was a lot more...
I would like to see an export option, e.g "Export as 5.0" in future releases...

**Comment by vincentmorneau** [comment]
Oh, I didn't know this. I voted.

@jeffreykemp so you updated the export file manually and changed 

```
 p_version_yyyy_mm_dd=>'2016.08.24'
,p_release=>'5.1.2.00.09'
```
to 
```
# APEX 5.0
 p_version_yyyy_mm_dd=>'2013.01.01'
,p_release=>'5.0.4.00.12'
```

?

**Comment by jeffreykemp** [comment]
No, I didn't do that. I created the plugin from scratch in my APEX 5.0 instance, based on the source files in github, and exported it from APEX 5.0 - so it's legitimate :)

It's only now, when we compare the files, that we can see there are only small differences between the versions (in the case of this plugin, at least).

**Comment by vincentmorneau** [comment]
Hum, that's good for a one time deal, but not good for maintenance.

@Dani3lSun I understand better now. How do you manage multiple APEX version on your plugins?

**Comment by jeffreykemp** [comment]
I'm happy to continue maintenance of the backport going forward.

I can use github changes to detect and make the same changes in the backport. Note that most of the plugin is in the form of render.sql, js and css files which I can copy-and-paste directly. The only significant work is updating plugin attributes and select list values.

Eventually I expect the 5.0 version will be less required over time as people upgrade (myself included) and it can be retired.

**Comment by vincentmorneau** [comment]
@jeffreykemp I would appreciate that.

I'll finalize the new render function and I'll let you know so you can update yours.

**Comment by Dani3lSun** [comment]
@vincentmorneau normally I create the plugin with the lowest APEX version I will support. Atm this is in most cases APEX 5. So my plugin development env is on APEX 5.0.4...

**Comment by vincentmorneau** [comment]
Makes sense. And upon release you simply import it back into 5.1 and provide all export files. Thanks. Now I gotta get myself a 5.0.4 environment...

**Comment by Dani3lSun** [comment]
@vincentmorneau I export the plugin with APEX 5, so it´s working in APEX 5.1 out-of-the-box. You don´t need to export it with 2 versions, thus all higher versions can use the export files that are created with an lower version, vice versa does not work. So you can´t export with 5.1 and use this export file in 5.0...

**Comment by jeffreykemp** [comment]
If you need one I can give you a workspace on my 5.0.4 env.

**Comment by vincentmorneau** [comment]
Jeffrey, I was finally able to setup a proper 5.0.4 environment. I will continue maintaining it in the future, as it will be easier for maintenance.

Thanks so much for making the 5.0.x compatible version. I started off of it.

**Comment by jeffreykemp** [comment]
thanks

**Pull request closed without merging**
